name: Deploy Laravel App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Latest code pull 
        run: |
          cd /home/zain/laravel-project/task-manager
          git pull origin main

      - name: Composer dependencies install 
        run: |
          cd /home/zain/laravel-project/task-manager
          composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Laravel caches clear 
        run: |
          cd /home/zain/laravel-project/task-manager
          php artisan config:clear
          php artisan route:clear
          php artisan view:clear

      - name: Migrations run 
        run: |
          cd /home/zain/laravel-project/task-manager
          php artisan migrate --force

      - name: Production caches 
        run: |
          cd /home/zain/laravel-project/task-manager
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Permissions fix 
        run: |
          cd /home/zain/laravel-project/task-manager
          sudo chown -R $USER:www-data storage bootstrap/cache
          sudo chmod -R 775 storage bootstrap/cache
